### ISSUE TITLE
Release cycle inconsistency

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-websites/www.ubuntu.com#3917]
Hi,

On the release-cycle page there are some inconsistencies. Please update:

- [x] "Ubuntu lts release support" - should LTS not always be capitalized?
- [x] I don't understand why the kernel section shows "Matching openstack release support"? I think this should be showing the time a kernel is supported, not OpenStack?
- [x] Update kernel section wording for "Extended support for customers" to match Ubuntu releases: "Extended security maintenance for customers"
- [x] "Matching openstack release support" - should OpenStack not always have a capital "O" and "S"?
- [x] Ubuntu 12.01.0 LTS (v3.2) ?
- [x] OpenStack chart no longer references backport and LTS release
- [x] Extend 12.04 ESM
- [x] OpenStack release cycles switched (mostly) to Feb/Aug

---
*Reported from: https://www.ubuntu.com/about/release-cycle*

**Comment by frankiegranato** [comment]
@cjohnston1158 As discussed over IRC, I think you should make these edits in the copydoc itself: https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit# 
I'm scheduling my team to work on this page in our next iteration of work (commencing next week)

**Comment by frankiegranato** [comment]
@cjohnston1158
My notes from our meeting (2018-09-04) about 'release-cycle updates':

This work concerns the "Ubuntu Release Cycle" 
CJ is requesting amendments to page (
Copydoc: https://docs.google.com/document/d/1-l3B7AoyDoETaL80UhlfEWCVKmMWPdy3zoF5LpsGcYQ/edit
url: https://www.ubuntu.com/about/release-cycle

CJ suggested that we use Mark's "conceptual" release cadence diagram on the /about page under the heading "Ubuntu Releases" where it talks about release cadences - perhaps under the paragraph that talks about "scheduled releases on a predictable cadence". I agree that this would be a useful place to display Mark's diagram.

Re the /about/release-cycle page. CJ says that, in his experience, customers who visit this page are looking for start and end dates. These customers are from procurement or legal teams and are looking for precise and detailed information. 

Also, CJ has requested an amendment to the OpenStack release cycle diagram (on the /release-cycle page). Essentially, he needs S, T, U and V added to the chart. He will send us the dates we need to make this change. He needs this work completed by end of October.
