### ISSUE TITLE
Suru not responsive on /support

### ISSUE THREAD

**Issue by Greggless** [canonical-websites/www.ubuntu.com#4456]
## @2550
![image](https://user-images.githubusercontent.com/23459065/49219661-d8711380-f3cb-11e8-81a2-08b57db96c84.png)
![image](https://user-images.githubusercontent.com/23459065/49219777-330a6f80-f3cc-11e8-9a18-8621042701bc.png)

I know it's (maybe) a rarer case where a user's screen size is >1440px, but we should look to make the suru responsive regardless.

Unless it is advised that we remove suru's from _all_ page heroes

## Tasks
- [ ] Design assets - 1pt
- [ ] Update assets - 2pts

---
*Reported from: https://www.ubuntu.com/support*

**Comment by anasereijo** [comment]
Hi Greg, wow this is quite old, thanks for finding out!
I can design and save down a responsive suru background. 
I will add this to next iteration's backlog.
thanks

**Comment by anasereijo** [comment]
- [ ] Make "Ubuntu Advantage commercial support" background `white`

<img width="1440" alt="screenshot 2019-01-30 at 15 21 01" src="https://user-images.githubusercontent.com/36884067/51991355-dba77f00-24a2-11e9-81d5-9e220fe3ffeb.png">


- [ ] Make "Community support" background `#f7f7f7`

<img width="1440" alt="screenshot 2019-01-30 at 15 21 34" src="https://user-images.githubusercontent.com/36884067/51991449-0abdf080-24a3-11e9-904b-7caf67ed3810.png">

**Comment by anasereijo** [comment]
@anthonydillon can you please make these changes? thank you
